name:                language-lyapas
version:             0.1.0.0
license:             GPL3
author:              "d86leader"
maintainer:          "d86leader@mail.com"

synopsis: "Analysis and generation of lyapas code"
description:
  " A haskell library for analysis and generation of lyapas code.
  It features a parser for a most common subset of vЛЯПАС
  and an interpreter for the intermediate representation.
  Soon to have a compiler too!
  "
category: Language

library:
  source-dirs:         src
  ghc-options:
  - -Wall -Wcompat
  dependencies:
  - base
  - data-default-class
  - megaparsec >= 9.0.0
  - mono-traversable
  - parser-combinators
  - text
