name:                language-lyapas
version:             0.1.0.0
license:             GPL-3
author:              "d86leader"
maintainer:          "d86leader@mail.com"

category: Language
synopsis: "Analysis and generation of lyapas code"
description:
  " A haskell library for analysis and generation of lyapas code.
  It features a parser for a most common subset of vЛЯПАС
  and an interpreter for the intermediate representation.
  Soon to have a compiler too!
  "

library:
  source-dirs:         src
  ghc-options:
  - -Wall -Wcompat
  default-extensions: OverloadedStrings LambdaCase BangPatterns
  dependencies:
  - base
  - bytestring
  - data-default-class
  - clock
  - exceptions
  - hashable
  - megaparsec >= 9.0.0
  - mono-traversable
  - mtl
  - optics-core
  - optics-extra
  - optics-th
  - parser-combinators
  - random
  - text
  - transformers
  - unordered-containers
  - vector
